export default {
  sortByPrice: ' Sort By Price',
  search: 'Search',
  ascSort: 'sort-alphabetical-ascending',
  descSort: 'sort-alphabetical-descending',
  closeIcon: 'close',
  usersIcon: 'account-group',
  listIcon: 'view-list',
  bridgeIcon: 'bridge',
  noMatchFound: 'No Match Found For',
  randomUsers: 'Random Users',
  noUsers: 'No more users at the moment',
  listEmpty: 'No Data at the moment',
  refresh: 'Refresh',
  noInternet: "Oops your're not connected to internet",
};
